image: node:16.5.0
stages:
  - build
build project:
  stage: build
  script:
    - yarn install
    - yarn install -g gatsby-cli
    - gatsby build
  artifacts:
    paths:
      - public

test artifact:
  image: alpine
  stage: test
  script:
    - grep -q "Gatsby" ./index.html


